<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Login</h1>
    <?php
        $dados = $this->view->date;
        var_dump($dados);
        foreach ($this->view->date as $key => $date) 
        {
            echo $date . "<br>";
        }
    ?>
</body>
</html>